#!/bin/bash

# Fix SSH auth socket location so agent forwarding works with screen.
if [ -n "${SSH_AUTH_SOCK+x}" ] ; then
  ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
elif [ -h ~/.ssh/ssh_auth_sock ] && [ ! -e ~/.ssh/ssh_auth_sock ] ; then
  # broken symlink
  rm ~/.ssh/ssh_auth_sock
fi

# Taken from the sshd(8) manpage.
if read -r proto cookie && [ -n "${DISPLAY+x}" ] ; then
  if [ "$(echo "$DISPLAY" | cut -c1-10)" = 'localhost:' ] ; then
    # X11UseLocalhost=yes
    echo add "unix:$(echo "$DISPLAY" | cut -c11-)" "$proto" "$cookie"
  else
    # X11UseLocalhost=no
    echo add "$DISPLAY" "$proto" "$cookie"
  fi | xauth -q -
fi
