#!/bin/bash

# Fix SSH auth socket location so agent forwarding works with screen.
if [ -n "${SSH_AUTH_SOCK+x}" ] ; then
  ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi

if [ -n "${DISPLAY+x}" ] ; then
  echo "# vim: ft=tmux" > ~/.ssh/display.conf
  echo setenv -g DISPLAY "$DISPLAY" >> ~/.ssh/display.conf
else
  : > ~/.ssh/display.conf
fi

# Taken from the sshd(8) manpage.
if read proto cookie && [ -n "${DISPLAY+x}" ] ; then
  if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ] ; then
    # X11UseLocalhost=yes
    echo add unix:`echo $DISPLAY | cut -c11-` $proto $cookie
  else
    # X11UseLocalhost=no
    echo add $DISPLAY $proto $cookie
  fi | xauth -q -
fi
